.PHONY: clean All

All:
	@echo "----------Building project:[ BOJ1406 - Debug ]----------"
	@cd "BOJ1406" && "$(MAKE)" -f  "BOJ1406.mk"
clean:
	@echo "----------Cleaning project:[ BOJ1406 - Debug ]----------"
	@cd "BOJ1406" && "$(MAKE)" -f  "BOJ1406.mk" clean
